name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.203' ]

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.203'
          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore and build (publish)
        run: msbuild /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:plugin_OpenVR:Publish /p:PublishProfile=plugin_OpenVR\Properties\PublishProfiles\FolderProfile.pubxml

      - name: Build the OpenVR driver
        run: msbuild /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:driver_Amethyst

      - name: Deploy the dotnet runtime
        run: Copy-Item -Path "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.5\*" -Destination plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\ -PassThru
        
      - name: Replace IJW and FXR with prepared prebuilts
        shell: pwsh
        run: |
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/comhost.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\comhost.dll")
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/coreclr.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\coreclr.dll")
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/hostfxr.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\hostfxr.dll")
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/hostpolicy.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\hostpolicy.dll")
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/ijwhost.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\ijwhost.dll")
           $(New-Object System.Net.WebClient).DownloadFile("https://github.com/KimihikoAkayasaki/runtime/releases/download/v7.0.0-fakefxr/nethost.dll", "plugin_OpenVR\bin\Release\net7.0\win10-x64\publish\Driver\Amethyst\bin\win64\nethost.dll")

      - name: Pack published files
        run: |
          cd plugin_OpenVR/bin/Release/net7.0/win10-x64/publish
          7z a plugin_OpenVR.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "plugin_OpenVR Build Artifact"
          files: |
            ./plugin_OpenVR/bin/Release/net7.0/win10-x64/publish/plugin_OpenVR.zip
            ./external/manifest.json